
export const indianStations: string[] = [
  "New Delhi (NDLS)",
  "Old Delhi Jn (DLI)",
  "Hazrat Nizamuddin (NZM)",
  "Anand Vihar Terminal (ANVT)",
  "Mumbai Central (MMCT)",
  "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
  "Dadar (DR)",
  "Bandra Terminus (BDTS)",
  "Lokmanya Tilak Terminus (LTT)",
  "Chennai Central (MAS)",
  "Chennai Egmore (MS)",
  "Tambaram (TBM)",
  "Kolkata Howrah Jn (HWH)",
  "Kolkata Sealdah (SDAH)",
  "Shalimar (SHM)",
  "KSR Bengaluru City Junction (SBC)",
  "Yesvantpur Jn (YPR)",
  "Bengaluru Cantt (BNC)",
  "Hyderabad Deccan Nampally (HYB)",
  "Secunderabad Jn (SC)",
  "Kacheguda (KCG)",
  "Pune Jn (PUNE)",
  "Jaipur Jn (JP)",
  "Gandhinagar Jaipur (GADJ)",
  "Ahmedabad Jn (ADI)",
  "Sabarmati BG (SBIB)",
  "Lucknow Charbagh NR (LKO)",
  "Lucknow Jn NER (LJN)",
  "Gomti Nagar (GTNR)",
  "Bhopal Jn (BPL)",
  "Rani Kamalapati (RKMP)",
  "Patna Jn (PNBE)",
  "Rajendra Nagar Terminal (RJPB)",
  "Danapur (DNR)",
  "Thiruvananthapuram Central (TVC)",
  "Ernakulam Jn (South) (ERS)",
  "Ernakulam Town (North) (ERN)",
  "Kozhikode Main (CLT)",
  "Guwahati (GHY)",
  "Kamakhya Jn (KYQ)",
  "Bhubaneswar (BBS)",
  "Puri (PURI)",
  "Nagpur Jn (NGP)",
  "Ajni (AJNI)",
  "Visakhapatnam Jn (VSKP)",
  "Agra Cantt (AGC)",
  "Agra Fort (AF)",
  "Varanasi Jn (BSB)",
  "Banaras (BSBS)",
  "Pt DD Upadhyaya Jn (Mughalsarai) (DDU)",
  "Amritsar Jn (ASR)",
  "Ludhiana Jn (LDH)",
  "Kalka (KLK)",
  "Chandigarh Jn (CDG)",
  "Shimla (SML)",
  "Kanpur Central (CNB)",
  "Prayagraj Jn (PRYJ)",
  "Indore Jn BG (INDB)",
  "Surat (ST)",
  "Vadodara Jn (BRC)",
  "Coimbatore Jn (CBE)",
  "Madurai Jn (MDU)",
  "Tiruchchirappalli Jn (TPJ)",
  "Vijayawada Jn (BZA)",
  "Raipur Jn (R)",
  "Ranchi Jn (RNC)",
  "Jodhpur Jn (JU)",
  "Udaipur City (UDZ)",
  "Jammu Tawi (JAT)",
  "Dehradun (DDN)",
  "Haridwar (HW)",
  "Mathura Jn (MTJ)",
  "Gorakhpur Jn (GKP)",
  "Mysuru Jn (MYS)"
];
